(defparameter *nodes* '((garden (you are in a beautiful garden. there is a well in front of you))
                        (living-room (you are in a living-room. a wizard snores on the couch))
                        (attic (you are in the attic. there is a giant welding torch in the corner.))))
(defparameter *edges* '((living-room (garden west door)
                         (attic upstairs ladder))
                        (garden (living-room east door))
                        (attic (living-room downstairs ladder))))

(defun describe-location (location nodes)
  (cadr (assoc location nodes)))
(defun describe-path (edge)
  `(there is a ,(caddr edge) going ,(cadr edge) from here.))
(defun describe-paths (location edges)
  (apply #'append (mapcar #'describe-path (cdr (assoc location edges)))))